#!/bin/bash
# Creates an animated GIF showcasing all 4 app modes from screenshots.
# Usage: bash scripts/create-demo-gif.sh
#
# Prerequisites:
#   - ffmpeg installed (brew install ffmpeg)
#   - Screenshots in docs/screenshots/ (generated by: npm run test:e2e -- --update-snapshots)
#
# To regenerate screenshots first:
#   npx electron-vite build && npx playwright test test/e2e/visual-regression.test.ts --update-snapshots

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SCREENSHOTS_DIR="$PROJECT_DIR/docs/screenshots"
OUTPUT="$PROJECT_DIR/docs/demo.gif"
TEMP_DIR=$(mktemp -d)

# Check prerequisites
if ! command -v ffmpeg &>/dev/null; then
  echo "Error: ffmpeg is required. Install with: brew install ffmpeg"
  exit 1
fi

for mode in vanilla island learn ocean; do
  if [ ! -f "$SCREENSHOTS_DIR/${mode}-mode.png" ]; then
    echo "Error: Missing $SCREENSHOTS_DIR/${mode}-mode.png"
    echo "Run: npm run test:e2e:update  to generate screenshots"
    exit 1
  fi
done

echo "Creating demo GIF from screenshots..."

# Add mode labels to each frame using ffmpeg drawtext
MODES=("vanilla" "island" "learn" "ocean")
LABELS=("Vanilla Mode" "Island Mode" "Learn Mode" "Ocean Mode")

for i in "${!MODES[@]}"; do
  mode="${MODES[$i]}"
  label="${LABELS[$i]}"
  # Create labeled frame with a banner at the top
  ffmpeg -y -i "$SCREENSHOTS_DIR/${mode}-mode.png" \
    -vf "drawbox=x=0:y=0:w=iw:h=40:color=black@0.7:t=fill,drawtext=text='${label}':fontsize=24:fontcolor=white:x=(w-text_w)/2:y=10" \
    "$TEMP_DIR/frame_${i}.png" 2>/dev/null || \
    cp "$SCREENSHOTS_DIR/${mode}-mode.png" "$TEMP_DIR/frame_${i}.png"
done

# Create GIF: 2 seconds per frame, looping
ffmpeg -y -framerate 0.5 -i "$TEMP_DIR/frame_%d.png" \
  -vf "fps=1,scale=800:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=128[p];[s1][p]paletteuse=dither=bayer" \
  "$OUTPUT" 2>/dev/null

# Clean up
rm -rf "$TEMP_DIR"

SIZE=$(du -h "$OUTPUT" | cut -f1)
echo "✅ Created $OUTPUT ($SIZE)"
echo "   4 frames: Vanilla → Island → Learn → Ocean (2s each)"
